### ISSUE TITLE
Model discussion

### ISSUE THREAD

**Issue by anlawande** [NCSU-CSC510/CMS-module#1]
As per discussion, here's the list of fields that "Post" and "Version" will have

Post
1. current_content : String
2. current_userid: String
3. current_timestamp: Timestamp
4. version_list: List<Version>
5. current_version: int/String

Version
1. content: String
2. version_id : int/String
3. userid: String
4. timestamp: Timestamp
5. state: DRAFT/PUBLISHED/ARCHIVE

**Comment by anishashetty** [comment]
So, the Post will have a List of references to the version Objects along with the reference to the current version.
The content f the post will be the content of the current_version object

**Comment by anlawande** [comment]
Agreed, post can just have a reference to the current version and have getter methods to access the properties

Post
1. version_list: List<Version>
2. current_version: Version

Version
1. content: String
2. version_id : int/String
3. userid: String
4. timestamp: Timestamp
5. state: DRAFT/PUBLISHED/ARCHIVE
