### ISSUE TITLE
Manager Objects

### ISSUE THREAD

**Issue by anishashetty** [NCSU-CSC510/CMS-module#11]
Create managers that will have below functions:
1. will be responsible for add objects 
2. delete objects 
3. Retrieve objects

**Comment by anlawande** [comment]
Will the managers actually contain the objects?

I'm thinking about from a searching perspective.

**Comment by anishashetty** [comment]
They will have a reference to say a global list of objects created

**Comment by SohanK** [comment]
What kind of objects are we talking about here?

**Comment by anlawande** [comment]
For example a postManager will be in charge of creating, deleting retrieving post objects (by postId).

But for simplicity of search, to not have to go through the manager we are considering making the list of managed objects global.

**Comment by anishashetty** [comment]
Currently working on PostManager for BDD.
I think the managers should be singleton objects.
Any thoughts?

**Comment by anlawande** [comment]
Agreed
