### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by anlawande** [NCSU-CSC510/CMS-module#12]
Since we are simultaneously working on 2 projects, lets decide on the projects structures to keep it uniform and comparable.

Source packages
edu.ncsu.cms.model
edu.ncsu.cms.helper
edu.ncsu.cms.managers
edu.ncsu.cms.search
edu.ncsu.cms.api
edu.ncsu.cms.useraccess
(others as needed)

For tests we can use edu.ncsu.cms.test.x where x is the module being tested

External libs go in lib/ folder

If no more changes, we can close this

**Comment by ptrived** [comment]
We are following the structure as specified above. So closing this issue.
