### ISSUE TITLE
Feature: Edit post

### ISSUE THREAD

**Issue by anishashetty** [NCSU-CSC510/CMS-module#3]
Feature: Edit Post
1. API call to edit post (Takes postId, versionId, content)
2. Call to postManager to edit post
3. Postmanager retrieves post using postId (handle id not found)
4. Postmanager retrieves version using versionId (handle id not found)
5. If version is in DRAFT state, replace content, if version is in PUBLISHED/ARCHIVED states, create new version in DRAFT state and replace content

**Comment by SohanK** [comment]
Edit a post:
1)Editing by Manger
2)Editing by Post Owner

Managing drafts of Edited posts
