### ISSUE TITLE
Feature : Publish a post

### ISSUE THREAD

**Issue by anishashetty** [NCSU-CSC510/CMS-module#6]

**Comment by anishashetty** [comment]
Proposed logic:
Publish a post if the following conditions are met:
1.current version of the post in a draft state
2.previous version is archived

@anlawande @SohanK  . Please provide your inputs

**Comment by anlawande** [comment]
@anishashetty  I think what you mean by 2 is that the version which is currently in published state will be moved to archived state?

**Comment by anishashetty** [comment]
Yes that is correct

**Comment by anishashetty** [comment]
Final changes pushed  to branch : develop
