### ISSUE TITLE
Setup TDD and BDD frameworks

### ISSUE THREAD

**Issue by anlawande** [NCSU-CSC510/CMS-module#9]
Setup JUnit for TDD
Setup JBehave for BDD.

If any other alternatives, discuss here

**Comment by anishashetty** [comment]
JBehave installatioion:
http://stackoverflow.com/questions/20733703/very-simple-step-by-step-jbehave-setup-tutorial

**Comment by anlawande** [comment]
Added Junit jars to TDD project

**Comment by anishashetty** [comment]
J-behave Tutorial:http://www.ryangreenhall.com/articles/bdd-by-example.html

**Comment by rroycho** [comment]
Mockito Tutorial for TDD:
http://docs.mockito.googlecode.com/hg/1.9.5/org/mockito/Mockito.html

Download jars from:
https://code.google.com/p/mockito/downloads/list

**Comment by anishashetty** [comment]
Closing Issue : the set up for both BDD and TDD has been finalised as
Jbehave for BDD,Mockito for TDD
